#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Swpider\Swpider;
use Symfony\Component\Console\Application;


//$swpider = new Swpider();
//$swpider->test();

$swpider = new Application();
$swpider->add(new Swpider);

$swpider->run();